# Le module NumPy

> vidéo

## Le tableau NumPy

L'objet de base du [module NumPy](https://numpy.org/) est un tableau à N-dimension (*ndarray*), que l'on appelera simplement tableau par la suite. Le plus simple pour créer un tableau est de convertir une liste en tableau. Pour cela, il faut utiliser la fonction `array()` du module NumPy:

In [8]:
# importation du module NumPy avec un alias np
import numpy as np

# création de la liste
ma_liste = [2.2, 6.1, 9.6, 1.3, 56.8, 8.0]

# création du tableau NumPy
mon_tableau = np.array(ma_liste)

# affichage du tableau et de son type
print(mon_tableau)
print(type(mon_tableau))

[ 2.2  6.1  9.6  1.3 56.8  8. ]
<class 'numpy.ndarray'>


Nous avons nouvel objet (ou type, c'est équivalent): le `numpy.ndarray`, ou tableau NumPy. Comme tout objet, il a des opérateurs, des fonctions et des méthodes associés.

En Python, un objet a des attributs auxquels on peut accéder en écrivant le nom de l'objet, suivi d'un point et du nom de l'attribut. Voici la liste des attributs d'un tableau NumPy:

attribut | description
--|--
t.ndim | nombre de dimensions
t.shape | taille du tableau dans chaque dimension
t.size | nombre total d'éléments
t.dtype | type des éléments du tableau

Regardons quelques attributs de `mon_tableau`:

In [21]:
# attribut nombre de dimensions (ndim)
mon_tableau.ndim

1

In [20]:
# attribut taille (size)
mon_tableau.size

6

In [24]:
# attribut forme (shape) -> résultat sous la forme d'un tuple
mon_tableau.shape

(6,)

<div class="alert alert-info">

**tuple**

Un [tuple](https://docs.python.org/fr/3/library/stdtypes.html#tuple) est un [type de données séquentiel](https://docs.python.org/fr/3/library/stdtypes.html#sequence-types-list-tuple-range) comme les listes. Cependant, alors que les listes sont muables (modifiables), les tuples sont immuables (non modifiables). On peut créer un tuple comme une liste, mais en utilisant une paire de parenthèse plutôt que des crochets. Pour différencier un tuple à un élément d'une simple paire de parenthèse, on ajoute une virgule après le chiffre, par exemple `a = (2,)`.

</div>

In [35]:
# attribut type des éléments (dtype)
mon_tableau.dtype

dtype('float64')

<div class="alert alert-info">

**dtype**

Numpy contient un nombre de types numériques beaucoup plus important que les types natifs de Python. De plus, il est possible de créer facilement de nouveaux types de données structurées. C'est pourquoi NumPy est adpaté au calcul scientifique. Le type par défaut d'un réel lorsque l'on crée un tableau est `float64`. Ce type est équivalent (en précision) au type `float` natif de Python. 64 bits correspond à la place que prend un scalaire en mémoire. On peut trouver une [liste des types natifs de NumPy](https://numpy.org/doc/1.18/reference/arrays.scalars.html#arrays-scalars-built-in).

</div>

### Exercice
La liste suivante contient le nombre d'habitants des 8 villes de France les plus peuplées: Paris, Marseille, Lyon, Toulouse, Nice, Nantes, Montpellier et Strasbourg (chiffres INSEE 2015)

In [11]:
nombre_habitants = [2206488, 861635, 513275, 471941, 342522, 303382, 277639, 277270]

1. Importer le module `numpy` sans alias.
2. Créer un tableau NumPy `np_nombre_habitants` à partir de la liste `nombre_habitants`.
3. Afficher le tableau créé et son attribut dtype.

In [38]:
# importer le module NumPy
import numpy

# création du tableau NumPy
np_nombre_habitants = numpy.array(nombre_habitants)

# afficher le tableau et son attribut dtype
print(np_nombre_habitants)
print(np_nombre_habitants.dtype)

[2206488  861635  513275  471941  342522  303382  277639  277270]
int64


## Opérations sur les tableaux
Un grand intérêt des tableaux NumPy par rapport aux listes Python, est la possibilité de les utiliser dans des expressions avec des opérateurs arithmétiques.

Les opérateurs arithmétiques que l'on a vu pour les types scalaires en Python (addition, soustraction, multiplication, etc...) s'appliquent **terme à terme** sur les tableaux.

Par exemple, si on multiplie un tableau par un scalaire, chaque élément du tableau est multiplié:

In [43]:
# création du tableau
mon_tableau = np.array([2.2, 6.0, 9.6])

# multiplication par un scalaire
print(0.5 * mon_tableau)

[1.1 3.  4.8]


On peut aussi utiliser des opérateurs arithmétiques dans des expressions avec **des tableaux de même forme**. Les opérations sont alors effectuées **terme à terme**: le 1er élément du 1er tableau avec le 1er élément du 2ème tableaux, etc..

In [45]:
# création de 2 tableaux
A = np.array([0, 5, 3])
B = np.array([2, 5, 1])

# addition terme à terme
print(A + B)

[ 2 10  4]


On peut former des expressions avec des tableaux de types numériques différents. Le résultat correspond alors au type le plus général ou le plus précis (propriété appelée *upcasting*). 

Par exemple, si on multiplie un tableau d'entiers avec un tableau de réels:

In [47]:
# création d'un tableau de réels
A = np.array([0.0, 5.0, 3.0], dtype='float64')

# création d'un tableau d'entiers
B = np.array([2, 5, 1], dtype='int64')

# multiplication terme à terme
C = A * B

# type des éléments du tableau résultant
print(C.dtype)

float64


### Exercice
Reprenons le tableau `np_nombre_habitants`, donnant le nombre d'habitants des 8 villes de France les plus peuplées (Paris, Marseille, Lyon, Toulouse, Nice, Nantes, Montpellier et Strasbourg). On définit un tableau donnant la superficie de ces mêmes ville (en km**2), dans le même ordre:

In [49]:
np_superficie = np.array([105.40, 240.62, 47.87, 118.30, 71.92, 65.19, 56.88, 78.26]) # km**2

1. Calculer la densité de population de chaque ville en nombre d'habitants/km**2. Affecter le résultat à une variable `np_densite` et afficher le résultat. Note: une seule expression sur une seule ligne est nécessaire.
2. Quel est le type des éléments du tableau `np_densité` (attribut dtype)

In [53]:
# calcul de la densité de population (hab/km**2)
np_densité = np_nombre_habitants / np_superficie

# afficher le résultat
print(np_densité)

# attribut dtype du résultat
print(np_densité.dtype)

[20934.42125237  3580.89518743 10722.26864424  3989.35756551
  4762.54171301  4653.81193435  4881.13572433  3542.93381038]
float64


## Indexation et tranche